UPDATE topics
SET cover_image = regexp_replace(cover_image, '\.png$', '.jpg')
WHERE cover_image LIKE '/images/topics/%.png'
  AND replace(cover_image, '.png', '.jpg') IN (
    '/images/topics/ai_boom.jpg',
    '/images/topics/amd.jpg',
    '/images/topics/anthropic.jpg',
    '/images/topics/apple.jpg',
    '/images/topics/artificial-intelligence-boom.jpg',
    '/images/topics/bitcoin-etf.jpg',
    '/images/topics/bitcoin-halving.jpg',
    '/images/topics/btc.jpg',
    '/images/topics/btc_halving.jpg',
    '/images/topics/chatgpt.jpg',
    '/images/topics/coinbase.jpg',
    '/images/topics/cpi.jpg',
    '/images/topics/crypto-regulation.jpg',
    '/images/topics/defi.jpg',
    '/images/topics/earnings-season.jpg',
    '/images/topics/earnings.jpg',
    '/images/topics/eth.jpg',
    '/images/topics/fed-interest-rates.jpg',
    '/images/topics/fed_rates.jpg',
    '/images/topics/google.jpg',
    '/images/topics/intc.jpg',
    '/images/topics/layer2.jpg',
    '/images/topics/meta.jpg',
    '/images/topics/microsoft-openai.jpg',
    '/images/topics/microsoft.jpg',
    '/images/topics/nvidia.jpg',
    '/images/topics/openai.jpg',
    '/images/topics/regulation.jpg',
    '/images/topics/smci.jpg',
    '/images/topics/sora.jpg',
    '/images/topics/spacex.jpg',
    '/images/topics/telegram.jpg',
    '/images/topics/tesla.jpg',
    '/images/topics/tiktok.jpg',
    '/images/topics/xai.jpg'
  );
